// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jziuymisxfpmchrmzpzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aXV5bWlzeGZwbWNocm16cHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTg3NTAsImV4cCI6MjA2MDEzNDc1MH0.Q2iUJn9njDWFGPoTgGOyvIwGcuqmeL_Q9iXgHOUYJYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);